services:
  express:
    container_name: inker-express
    build: ./Backend
    ports:
      - "3000:3000"
    volumes:
      -  ./Backend:/app
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo
      - redis
    command: "npm run dev"

  mongo:
    container_name: mongo-db
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password


  redis:
    container_name: "redis_container"
    image: "redis:7.4"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo-data:
  redis_data:
